[versions]
kotlin = "2.1.21"
#kotlin = "2.0.0"

openapi-generator = "7.12.0"
jackson = "2.18.3"
# kotlin-spring-ver = "1.9.25"
spring-boot = "3.5.6"
coroutines = "1.9.0"

# BASE
jvm-compiler = "17"
jvm-language = "21"

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-binaryCompatibilityValidator = "org.jetbrains.kotlinx:binary-compatibility-validator:0.13.2"
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
# kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.1" }

# SPRING ---
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version = "2.3.0" }
#spring-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }

# COROUTINES ---
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "coroutines" }
coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
coroutines-reactor-extentions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# KLOGGING ---
klogging = { module = "io.klogging:klogging-jvm",  version = "0.10.1"}

# Databases
db-cache4k = "io.github.reactivecircus.cache4k:cache4k:0.13.0"

# TESTS
test-spring-boot = { module = "org.springframework.boot:spring-boot-starter-test" }
test-spring-kafka = { module = "org.springframework.kafka:spring-kafka-test" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }

# SPRING ---
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencies = { id ="io.spring.dependency-management", version = "1.1.7" }
kotlin-sping = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" } # kotlin-spring-ver" }

