server:
  port: 8080

management:
  endpoint:
    env:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: info, env

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: app-spring

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    use-root-path: true
    urls:
      - name: picture-server
        url: open-api-postfull-images.yaml